"""initial

Revision ID: 00559f07c23b
Revises: 
Create Date: 2022-12-23 02:07:18.746518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00559f07c23b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
