"""regions

Revision ID: 656812465ce2
Revises: 
Create Date: 2022-12-24 17:35:26.227741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656812465ce2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
