"""added age field

Revision ID: ca24893fe01e
Revises: d061ed08ede5
Create Date: 2022-12-18 03:11:20.216437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca24893fe01e'
down_revision = 'd061ed08ede5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('p_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'p_age')
    # ### end Alembic commands ###
